//! Read-side listing use-case tests.

mod list_sessions_page_annotates_each_with_open_state_and_threads_route_by_id;
mod list_sessions_page_annotates_open_state_and_threads;
mod list_sessions_page_breaks_recency_ties_deterministically;
mod list_sessions_page_marks_a_bound_session_open_and_a_closed_one_not;
mod list_sessions_page_reproduces_recency_order_across_pages;
mod open_sends_for_lists_open_sends_and_rejects_unknown_session;
