#!/usr/bin/env bash
set -euo pipefail

# Rewrite the merged release PR description to use permanent tag links.
#
# Usage:
#   update-release-pr-links.sh <version>
#
# When the release PR body is generated by create-release-pr.sh, the
# compare link points at the temporary release branch (release/vX.Y.Z)
# because the tag does not exist yet. Once the release workflow has cut
# the tag, the branch is deleted and the compare link goes stale. This
# script finds the merged release PR for the given version and rewrites
# the compare link in its body to point at the permanent tag (vX.Y.Z).
#
# Environment variables:
#   GH_TOKEN - GitHub token for API access (required).

main() {
    local version="$1"
    local pr_number body

    pr_number=$(find_release_pr "$version")
    if [ -z "$pr_number" ]; then
        echo "No merged release PR found for v${version}; nothing to rewrite."
        return 0
    fi

    echo "Rewriting links on PR #${pr_number}..."

    body=$(gh pr view "$pr_number" --json body --jq '.body')
    body=$(echo "$body" | sed "s|\.\.\.release/v${version}|...v${version}|g")

    echo "$body" | gh pr edit "$pr_number" --body-file -
    echo "Done."
}

find_release_pr() {
    local version="$1"
    gh pr list \
        --state merged \
        --search "Release v${version} in:title" \
        --json number \
        --jq '.[0].number // empty'
}

main "$@"
