//! Settings → Storage worktree use-case tests.

mod list_worktree_dirs_marks_the_ones_a_session_works_in;
mod remove_worktree_dir_needs_force_for_a_dirty_or_unregistered_worktree;
mod remove_worktree_dir_refuses_a_path_outside_the_base;
mod remove_worktree_dir_refuses_a_worktree_a_session_works_in;
mod remove_worktree_dir_removes_a_clean_worktree_and_cleans_up;
mod support;
