[package]
name = "delta-wire"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
delta-model = { workspace = true }
delta-usecase = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ts-rs = { workspace = true }
