//! Claude Code hook handler tests.

mod ask_user_question_drives_a_question_notice;
mod ask_user_question_never_outlives_its_turn;
mod first_submit_registers_session;
mod message_display_streams_and_clears;
mod on_stop_routes_sync_by_hook_session_id;
mod pending_permission_is_queryable_live_state;
mod permission_request_registers_dialog_and_decision_resolves;
mod pre_tool_use_records_request_without_notifying;
mod session_end_for_bound_session_is_a_normal_end;
mod session_end_for_resuming_session_reports_failed;
mod session_end_for_unbound_spawn_reports_failed;
mod session_start_clear_and_compact_are_noops;
mod session_start_resume_marks_ready_without_dispatching;
mod session_start_startup_binds_pending_spawn;
mod session_start_then_user_prompt_bind_once;
mod session_start_unknown_session_is_a_safe_noop;
mod submit_registers_each_session_id_independently;
mod task_notification_prompt_is_not_external_input;
mod unknown_session_without_pending_spawn_registers_external_closed;
mod unmatched_prompt_is_external_input;
