//! Session-lifecycle use-case tests.

mod clear_session_input_clears_open_pane_and_noops_when_closed;
mod close_session_kills_the_pane_and_keeps_the_data;
mod close_session_known_but_not_open_is_a_noop;
mod close_session_unknown_id_is_session_not_found;
mod ensure_session_is_idempotent_while_a_session_is_bound;
mod ensure_session_is_idempotent_while_a_spawn_is_live;
mod ensure_session_spawns_a_session_in_its_own_workdir_when_absent;
mod new_session_with_invalid_workdir_spawns_nothing;
mod new_session_with_valid_workdir_launches_there;
mod new_session_without_workdir_falls_back_to_base_token;
mod open_session_is_a_noop_when_already_open;
mod open_session_missing_transcript_is_resume_unavailable;
mod open_session_resumes_with_resume_argv_then_send_uses_normal_path;
mod open_session_unknown_id_is_session_not_found;
mod same_workdir_spawns_bind_to_their_own_session_each;
mod spawn_skips_tmux_session_names_already_in_use;
mod user_prompt_binds_pending_spawn_by_session_id;
