//! Attribution-fold semantics, tested directly on the pure function.
//!
//! These pin the line-classification and thread-assignment rules without any
//! store or actor: ports of the logic-heavy parts of the `delta-usecase`
//! sync test suite, plus the seams that suite could not reach (effect order,
//! send non-consumption, state threading).

#[path = "../support/mod.rs"]
mod support;

mod a_background_completion_seeded_from_an_earlier_window_lands_on_its_launch;
mod a_background_task_completion_is_attributed_to_its_launching_thread;
mod a_branch_send_echo_attributes_user_and_assistant_to_the_child;
mod a_compact_summary_line_inherits_carry_and_does_not_consume_the_outstanding_send;
mod a_denied_background_launch_completes_from_its_errored_tool_result;
mod a_denied_tool_result_resolves_its_permission_as_denied;
mod a_forked_skill_completion_notification_clears_the_launch_by_task_id;
mod a_forked_skill_launch_is_attributed_to_the_launching_thread;
mod a_forked_skill_launch_lights_a_background_indicator_and_records_the_launch;
mod a_forked_skill_launch_with_an_unusable_body_emits_no_launch_effects;
mod a_human_line_whose_text_differs_still_consumes_the_outstanding_send;
mod a_human_line_with_no_outstanding_send_resets_carry_to_main;
mod a_line_with_no_forked_skill_launch_element_emits_no_launch_effects;
mod a_local_command_group_folds_to_meta_resolves_its_send_and_ends_the_turn;
mod a_local_command_name_line_consumes_a_slash_command_send_of_another_name;
mod a_local_command_name_line_leaves_a_plain_prompt_send_outstanding;
mod a_local_command_with_no_outstanding_send_just_folds_to_meta;
mod a_modern_agent_tool_use_with_no_run_in_background_flag_is_treated_as_background;
mod a_namespaced_local_command_name_line_matches_a_short_form_send;
mod a_plain_send_echo_lands_on_its_thread_and_marks_the_send_matched;
mod a_queued_command_matching_a_send_attributes_prompt_and_reply_to_the_child;
mod a_queued_replay_after_compact_matches_its_send_instead_of_folding_to_meta;
mod a_queued_replay_after_compact_without_a_matching_send_lands_on_main_as_user;
mod a_quoted_forked_skill_element_on_a_human_or_assistant_line_mints_no_launch;
mod a_real_prompt_after_a_local_command_is_an_ordinary_user_turn;
mod a_running_or_errored_task_output_retrieval_leaves_the_launch_running;
mod a_successful_background_launch_result_does_not_complete_the_subagent;
mod a_task_notification_carrying_only_task_id_resolves_via_the_tool_result_upgrade;
mod a_task_notification_carrying_only_tool_use_id_still_completes;
mod a_task_notification_mid_branch_inherits_carry_and_does_not_reset_to_main;
mod a_task_output_retrieval_completes_the_background_launch_it_names;
mod a_task_output_retrieval_folded_after_its_tool_use_window_still_completes;
mod a_tool_result_mid_branch_stays_on_the_branch_and_resolves_its_permission;
mod an_api_error_line_inherits_carry_and_emits_turn_aborted_without_consuming_the_send;
mod an_errored_result_for_a_non_launch_tool_emits_no_completion;
mod an_unknown_background_completion_falls_back_to_inheriting_carry;
mod an_unknown_command_notice_consumes_a_slash_command_send_of_another_name;
mod an_unknown_command_notice_leaves_a_plain_prompt_send_outstanding;
mod an_unknown_command_notice_matches_a_send_carrying_args;
mod an_unknown_command_notice_resolves_its_send_and_ends_the_turn;
mod an_unknown_command_notice_with_no_outstanding_send_just_surfaces;
mod an_unmatched_queued_command_inherits_the_carry_thread;
mod auto_compact_finished_is_not_emitted_for_non_compact_summary_lines;
mod both_interrupt_marker_variants_are_recognized;
mod non_human_lines_inherit_carry;
mod send_text_comparison_ignores_surrounding_whitespace;
mod state_threads_across_batches_exactly_like_one_fold;
mod the_interrupt_marker_inherits_carry_and_does_not_consume_the_outstanding_send;
